image: node:8

stages:
  - build

build:
  stage: build
  before_script:
    - curl https://install.meteor.com | sh
    - npm install --silent
  script:
    - meteor build --directory ../output --allow-superuser --server-only
