image: mongo

stages:
  - build
  - deploy

staging:
  stage: deploy
  before_script:
    - apt-get update -qy
    # General dependencies
    - apt-get install -y curl
    # Dependencies for deployment to heroku.com
    - apt-get install -y git
    # Dependencies for import script
    - apt-get install -y software-properties-common
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs
  script:
    # Deploy to heroku.com
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=kassna-develop --api-key=$HEROKU_STAGING_API_KEY
    # Import fixtures
    - npm run import:fixtures
  only:
    - develop

build:
  stage: build
  before_script:
    - apt-get update -qy
    # Dependencies for npm
    - apt-get install -y curl
    - apt-get install -y software-properties-common
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs
    - apt-get install -y git
    # Meteor and installing npm packages
    - curl https://install.meteor.com | sh
    - npm install --silent
  script:
    - meteor build --directory ../output --allow-superuser --server-only
  except:
    - develop
